---
title: "Belize Manuscript"
author: "Fangyi Tan"
date: "2025-07-11"
output: html_document
---

```{r setup, include=FALSE}

library(dplyr)
library(reslr)
library(data.table)
library(ggplot2)
library(readxl)
library(RColorBrewer)
library(khroma)
library(ggridges)
```


# NI Spline model 

## Sensitivity test: nseg settings

```{r run GR19C1 full dataset with different nseg settings}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)
GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")

runNISplineNseg = function(nseg){
  
  # run NI spline model
  GR19C1_NIspline_nseg=reslr_mcmc(GR19C1_input,
           model_type = 'ni_spline_t',
          spline_nseg = nseg,
          n_iterations = 5000,
          n_burnin = 500,
          n_thin=5,
          n_chains=2)

  # save output data frame
  GR19C1_NIspline_nseg_df = GR19C1_NIspline_nseg$output_dataframes %>% mutate(nseg=nseg)
  return(GR19C1_NIspline_nseg_df)
}

####################### UNCOMMENT TO RE-RUN ##############################
# # run spline model for different nseg values
# toapply = as.list(seq(from=5,by=1,to=15)) # list of nseg values to run for
# GR19C1_test_nseg = lapply(toapply,runNISplineNseg) %>% rbindlist()
# 
# # save output
# save(GR19C1_test_nseg,file='results/NIspline/GR19C1_test_nseg.Rdata')
# write.csv(GR19C1_test_nseg,'results/NIspline/GR19C1_test_nseg.csv')
##########################################################################

# load output 
load('results/NIspline/GR19C1_test_nseg.Rdata')

# reverse names for upr and lwr as default output is reversed
GR19C1_test_nseg = GR19C1_test_nseg %>% rename(lwr=upr,upr=lwr,rate_lwr=rate_upr,rate_upr=rate_lwr)

# plot 
GR19C1_test_nseg = GR19C1_test_nseg %>% mutate(nseglabel=paste('nseg:',nseg))
GR19C1_test_nseg = GR19C1_test_nseg %>% mutate(nseglabel=factor(nseglabel,levels=unique(GR19C1_test_nseg$nseglabel)))

p_RSL = ggplot() +
  # plot data
  geom_rect(data=GR19C1,aes(xmin=Age-Age_up_er_2sd,xmax=Age+Age_up_er_2sd,
                ymin=RSL-RSLer_up_2sd,ymax=RSL+RSLer_up_2sd),alpha=0.5,fill='grey80')+
  geom_point(data=GR19C1,aes(x=Age,y=RSL),size=0.01,color='grey20') +
  # plot model
  geom_path(data=GR19C1_test_nseg,aes(x=Age_BP,y=pred),color='lightskyblue',linewidth=0.3) +
  geom_ribbon(data=GR19C1_test_nseg,aes(x=Age_BP,ymin=lwr,ymax=upr),alpha=0.5,fill='lightskyblue')+ # 2 sigma
  theme_classic()+
  scale_x_reverse(labels = function(x) x / 1000)+
  labs(x='Age (BP)',y='RSL (m)') +
  facet_wrap(~nseglabel)

p_rates = ggplot(data=GR19C1_test_nseg) +
  geom_path(aes(x=Age_BP,y=rate_pred),color='lightskyblue',linewidth=0.3) +
  geom_ribbon(aes(x=Age_BP,ymin=rate_lwr,ymax=rate_upr),alpha=0.5,fill='lightskyblue') + # 2 sigma
  theme_classic()+
  scale_x_reverse(labels = function(x) x / 1000)+
  labs(x='Age (BP)',y='RSL rate (mm/yr)') +
  facet_wrap(~nseglabel)

p = cowplot::plot_grid(p_RSL,p_rates,nrow=2,align='hv')
p

ggsave('figures/NIspline/GR19C1 NIspline model fit nseg-sensitivity.pdf',p,height=7,width=6)
```

```{r cross validation checks on nseg settings for NI Spline model}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)

runCV = function(nseg){
  
  # run 10-fold cross validation for a given nseg setting
  cv = cross_val_check(data = GR19C1,
                      model_type ="ni_spline_t",
                      spline_nseg = nseg, # User the package to calculate the number of knots
                      n_fold = 10, # n_fold allows the user to alter the cross validation, i.e. 3, 5, 10 fold
                      seed = 42, #To reproducible results,seed stores the output of the random selection
                     n_iterations = 5000,
                     n_burnin = 500,
                     n_thin=5,
                     n_chains=2)
  
  # extract formatted data frame of cross-validation results
  cv_df = cv$CV_model_df %>% mutate(nseg=nseg)
  
  return(cv_df)
}

######################## UNCOMMENT TO RE-RUN ##############################
# # run cross-validation for different nseg values
# toapply = as.list(seq(from=5,by=1,to=15)) # list of nseg values to run cross-validation for
# GR19C1_cv_nseg = lapply(toapply,runCV) %>% rbindlist()
# 
# # calculate RMSE for each nseg setting
# GR19C1_cv_nseg = GR19C1_cv_nseg %>% group_by(nseg) %>% mutate(RMSE = sqrt(mean((true_RSL-pred_RSL)^2))) %>% ungroup()
# 
# # save cv output for plotting comparison
# write.csv(GR19C1_cv_nseg,'results/NIspline/GR19C1 NIspline model CV nseg.csv')

###########################################################################

GR19C1_cv_nseg = read.csv('results/NIspline/GR19C1 NIspline model CV nseg.csv')

# plot output 
GR19C1_cv_nseg = GR19C1_cv_nseg %>% mutate(nseglabel=paste('nseg:',nseg))
GR19C1_cv_nseg = GR19C1_cv_nseg %>% mutate(nseglabel=factor(nseglabel,levels=unique(GR19C1_cv_nseg$nseglabel)))

p_NIspline_cv_nseg = ggplot(data=GR19C1_cv_nseg) +
  geom_point(aes(x=true_RSL,y=pred_RSL),color='lightskyblue',size=0.1) +
  geom_segment(aes(x=true_RSL,xend=true_RSL,y=lwr_PI,yend=upr_PI),color='lightskyblue',alpha=0.5) +
  geom_text(aes(x=-8,y=-1,label=paste('RMSE:',round(RMSE,digits=4),'m')),size=3)+
  geom_abline(slope=1)+
  theme_classic() +
  labs(x='True RSL(m)',y='Predicted RSL (m)') +
  facet_wrap(~nseglabel,nrow=4)
p_NIspline_cv_nseg

ggsave('figures/NIspline/GR19C1 NIspline model CV nseg.pdf',p_NIspline_cv_nseg,height=7,width=7)

# print best-fitting nseg setting 
paste('The lowest RMSE in predictions comse from using nseg value:',unique(GR19C1_cv_nseg$nseg[which(GR19C1_cv_nseg$RMSE==min(GR19C1_cv_nseg$RMSE))]))

```

## Nseg=14 Full dataset 

```{r run NI Spline model GR19C1 nseg14}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)
GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")

set.seed(42)
# run NI spline model
GR19C1_NIspline_nseg14=reslr_mcmc(GR19C1_input,
           model_type = 'ni_spline_t',
          spline_nseg = 14,
          n_iterations = 5000,
          n_burnin = 500,
          n_thin=5,
          n_chains=2)

# plot results
est_plot = plot(GR19C1_NIspline_nseg14,plot_type = "model_fit_plot",plot_caption = FALSE)
rate_plot = plot(GR19C1_NIspline_nseg14,plot_type = "rate_plot",plot_caption = FALSE)
GR19C1_NIspline_Plot = cowplot::plot_grid(est_plot,rate_plot,nrow=2,align='hv')
GR19C1_NIspline_Plot

ggsave('figures/NIspline/GR19C1 NIspline model fit nseg14.pdf',GR19C1_NIspline_Plot,width=8,height=8)

# save output data frame
GR19C1_NIspline_nseg14_df = GR19C1_NIspline_nseg14$output_dataframes
write.csv(GR19C1_NIspline_nseg14_df,'results/NIspline/GR19C1 NIspline model nseg14.csv')
```

## Nseg=14 variable age-depth model inputs 

```{r run NI Spline model GR19C1 nseg14 sensitivity to age-depth model}

# load RSL data
GR19C1runs = read.csv('data/GR19C1_RSL_sensitivityruns_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)


# function to run NI spline model on a given RSL sensitivity run
runNISpline = function(x) {
  
  GR19C1 = filter(GR19C1runs,model==x)
  
  # load data 
  GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")
  
  cat(sprintf("Started run %s at %s\n", x, Sys.time()))

  # run NI spline model
  GR19C1_NIspline=reslr_mcmc(GR19C1_input,
           model_type = 'ni_spline_t',
          spline_nseg = 14,
          CI = 0.95,# Size of the credible intervals and prediction intervals
          n_iterations = 5000,
          n_burnin = 500,
          n_thin=5,
          n_chains=2)
  
  output = GR19C1_NIspline$output_dataframes %>% mutate(model=unique(GR19C1$model),removalID=unique(GR19C1$removalID))
  
  return(output)
  
}

# list of unique models to run NI Spline for 
sensitivityruns = as.list(unique(GR19C1runs$model))

######################### UNCOMMENT TO RE-RUN #########################################
# # run NI spline for all sensitivy runs
# GR19C1_NIspline_sensitivityruns = lapply(sensitivityruns,runNISpline) %>% rbindlist()
# 
# # save output
# save(file='results/NIspline/GR19C1_NIspline_nseg14_sensitivityruns.Rdata',GR19C1_NIspline_sensitivityruns)
# write.csv(GR19C1_NIspline_sensitivityruns,'results/NIspline/GR19C1_NIspline_nseg14_sensitivityruns.csv')
######################################################################################

# load output
load('results/NIspline/GR19C1_NIspline_nseg14_sensitivityruns.Rdata')
GR19C1_NIspline_sensitivityruns = GR19C1_NIspline_sensitivityruns %>% 
  mutate(removalIDlabel = paste0('n=',sub(".*_","",removalID)))
 
# reverse names for upr and lwr as default output is reversed
GR19C1_NIspline_sensitivityruns = GR19C1_NIspline_sensitivityruns %>% rename(lwr=upr,upr=lwr,rate_lwr=rate_upr,rate_upr=rate_lwr)

# plot RSL faceted
p_RSL = 
  ggplot(data=GR19C1_NIspline_sensitivityruns) +
  # geom_path(aes(x=Age_BP,y=pred,color=model),linewidth=0.1) +
  geom_ribbon(aes(x=Age_BP,ymin=lwr,ymax=upr,fill=model),alpha=0.8) + # 2 sigma
  # geom_vline(aes(xintercept=3000),linetype='dashed')+
  # geom_vline(aes(xintercept=7600),linetype='dashed')+
  facet_wrap(~removalIDlabel) +
  scale_x_reverse() +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_batlow(discrete=TRUE)+
  scale_fill_batlow(discrete=TRUE) +
  labs(x='Age (BP)',y='RSL (m)')


# plot rates faceted
p_rates = 
  ggplot(data=GR19C1_NIspline_sensitivityruns) +
  # geom_path(aes(x=Age_BP,y=rate_pred,color=model),linewidth=0.1) +
  geom_ribbon(aes(x=Age_BP,ymin=rate_lwr,ymax=rate_upr,fill=model),alpha=0.8) + # 2 sigma
  # geom_vline(aes(xintercept=3000),linetype='dashed')+
  # geom_vline(aes(xintercept=7600),linetype='dashed')+
  facet_wrap(~removalIDlabel) +
  scale_x_reverse() +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_batlow(discrete=TRUE)+
  scale_fill_batlow(discrete=TRUE) +
  labs(x='Age (BP)',y='Rate (mm/yr)')


p=cowplot::plot_grid(p_RSL,p_rates,nrow=2,align='hv')
p

ggsave('figures/NIspline/GR19C1 NIspline model fit nseg14 agedepth_sensitivity.pdf',p,height=8,width=6)

```

# EIV-IGP model 

```{r run EIV-IGP model GR19C1 default}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)
GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")

# run EIV-IGP model
GR19C1_EIVIGP=reslr_mcmc(GR19C1_input,
           model_type = 'eiv_igp_t')

# export output as .csv file
GR19C1_EIVIGP_output = GR19C1_EIVIGP$output_dataframes
write.csv(GR19C1_EIVIGP_output,'results/Belize/GR19C1_EIVIGP_defaultsettings.csv')

# plot results 

p_est = ggplot(data=GR19C1_EIVIGP_output) +
  geom_path(aes(x=Age_BP,y=pred)) +
  geom_ribbon(aes(x=Age_BP,ymin=lwr,ymax=upr),alpha=0.2) + # 2 sigma
  theme_classic() +
  scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000))

p_rates = ggplot(data=GR19C1_EIVIGP_output) +
  geom_path(aes(x=Age_BP,y=rate_pred)) +
  geom_ribbon(aes(x=Age_BP,ymin=rate_lwr,ymax=rate_upr),alpha=0.2) + # 2 sigma
  theme_classic() +
  scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000))

GR19C1_EIVIGP_Plot = cowplot::plot_grid(p_est,p_rates,nrow=2,align='hv')
GR19C1_EIVIGP_Plot

ggsave('figures/Belize/GR19C1 EIVIGP defaultsettings.pdf',GR19C1_EIVIGP_Plot,width=7,height=6)

```


```{r run EIV-IGP model GR19C1 subsample every nth sample}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput_21Jul25.csv') %>% rename(Age_err = AgeError,RSL_err=RSLError)

# run EIV-IGP model
toapply = as.list(seq(from=2,to=10,by=1))

runEIVIGP = function(x) {

  index = seq(from=1,by=x,to=nrow(GR19C1)) # index to subsample
  subsample = slice(GR19C1,index) # subsample/ thin input dataset

  # load data
  GR19C1_input=reslr_load(subsample,input_age_type = "BP")

  # run EIV-IGP model
  GR19C1_EIVIGP=reslr_mcmc(GR19C1_input,
           model_type = 'eiv_igp_t')

  # export output as .csv file
  GR19C1_EIVIGP_output = GR19C1_EIVIGP$output_dataframes
  filepath = paste0('results/GR19C1_EIVIGP_thinned',x,'.csv')
  write.csv(GR19C1_EIVIGP_output,filepath)
}

# run EIV-IGP model
lapply(toapply,runEIVIGP)

# load result of thinning sensitivity test
loadEIVIGP = function(x) {
  filepath = paste0('results/GR19C1_EIVIGP_thinned',x,'.csv')
  read.csv(filepath) %>% mutate(thin=as.factor(x))
}
EIVIGP_sensitivityresults = lapply(toapply,loadEIVIGP) %>% rbindlist()

# add default run
defaultrun=read.csv('results/GR19C1_EIVIGP_defaultsettings.csv') %>% mutate(thin=as.factor(0))
EIVIGP_sensitivityresults = bind_rows(defaultrun,EIVIGP_sensitivityresults)

# plot
p_est = ggplot(data=EIVIGP_sensitivityresults) +
  geom_path(aes(x=Age_BP,y=pred)) +
  geom_ribbon(aes(x=Age_BP,ymin=lwr,ymax=upr),alpha=0.2) +
  geom_vline(aes(xintercept=7600),linetype='dashed')+
  theme_classic() +
  scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000)) +
  scale_fill_hawaii(discrete=TRUE,reverse=TRUE) +
  scale_color_hawaii(discrete=TRUE,reverse=TRUE) +
  labs(x='Age (BP)',y='RSL (m)') +
  facet_wrap(~thin,ncol=5)

p_rates = ggplot(data=EIVIGP_sensitivityresults) +
  geom_path(aes(x=Age_BP,y=rate_pred)) +
  geom_ribbon(aes(x=Age_BP,ymin=rate_lwr,ymax=rate_upr),alpha=0.2) +
  geom_vline(aes(xintercept=7600),linetype='dashed')+
  theme_classic() +
  scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000)) +
  scale_fill_hawaii(discrete=TRUE,reverse=TRUE) +
  scale_color_hawaii(discrete=TRUE,reverse=TRUE) +
  labs(x='Age (BP)',y='RSL rate (mm/yr)') +
  facet_wrap(~thin,ncol=5)

GR19C1_EIVIGP_Plot = cowplot::plot_grid(p_est,p_rates,nrow=2,align='hv')
GR19C1_EIVIGP_Plot

ggsave('figures/Belize/GR19C1 EIVIGP thinning sensitivity.pdf',GR19C1_EIVIGP_Plot,width=10,height=6)

```

```{r run EIV-IGP model GR19C1 sensitivity test for smoothing degree}

# BelizeData = read.csv('data/RSL_Bchron_Belize_19Jun25.csv') # load whole Belize database
# GR19C1 = slice(BelizeData,1:151) # filter our record only
# 
# # load data 
# GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")
# 
# # run EIV-IGP model
# toapply = as.list(seq(from=0.1,to=0.9,by=0.1))
# 
# runEIVIGP = function(x) {
#   
#   # run EIV-IGP model
#   GR19C1_EIVIGP=reslr_mcmc(GR19C1_input,
#            model_type = 'eiv_igp_t',
#            igp_smooth=x)
#   
#   # export output as .csv file
#   GR19C1_EIVIGP_output = GR19C1_EIVIGP$output_dataframes
#   filepath = paste0('results/GR19C1_EIVIGP_smoothed0',x*10,'.csv')
#   write.csv(GR19C1_EIVIGP_output,filepath)
# }
# 
# # lapply(toapply,runEIVIGP)
# 
# # load results 
# loadEIVIGP = function(x) {
#   filepath = paste0('results/GR19C1_EIVIGP_smoothed0',x*10,'.csv')
#   read.csv(filepath) %>% mutate(smooth=as.factor(x))
# }
# 
# EIVIGP_sensitivityresults = lapply(toapply,loadEIVIGP) %>% rbindlist()
# 
# # plot
# p_est = ggplot(data=EIVIGP_sensitivityresults) +
#   geom_path(aes(x=Age_BP,y=pred)) +
#   geom_ribbon(aes(x=Age_BP,ymin=lwr,ymax=upr),alpha=0.2) +
#   geom_vline(aes(xintercept=7600),linetype='dashed')+
#   theme_classic() +
#   scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000)) +
#   scale_fill_hawaii(discrete=TRUE,reverse=TRUE) +
#   scale_color_hawaii(discrete=TRUE,reverse=TRUE) +
#   labs(x='Age (BP)',y='RSL (m)') +
#   facet_wrap(~smooth,ncol=5)
# 
# p_rates = ggplot(data=EIVIGP_sensitivityresults) +
#   geom_path(aes(x=Age_BP,y=rate_pred)) +
#   geom_ribbon(aes(x=Age_BP,ymin=rate_lwr,ymax=rate_upr),alpha=0.2) +
#   geom_vline(aes(xintercept=7600),linetype='dashed')+
#   theme_classic() +
#   scale_x_reverse(breaks=seq(from=9000,to=0,by=-1000)) +
#   scale_fill_hawaii(discrete=TRUE,reverse=TRUE) +
#   scale_color_hawaii(discrete=TRUE,reverse=TRUE) +
#   labs(x='Age (BP)',y='RSL rate (mm/yr)') +
#   facet_wrap(~smooth,ncol=5)
# 
# GR19C1_EIVIGP_Plot = cowplot::plot_grid(p_est,p_rates,nrow=2,align='hv')
# GR19C1_EIVIGP_Plot
# 
# ggsave('figures/Belize/GR19C1 EIVIGP smoothness sensitivity.pdf',GR19C1_EIVIGP_Plot,width=10,height=6)

```

# EIV-CP model

```{r run EIV-CP model for GR/19/C1 with 2 changepoints}

# load data
GR19C1 = read.csv('data/RSLallages_Bchron_EIVIGPinput.csv') %>% rename(Age_err=AgeError,RSL_err=RSLError)
GR19C1_input=reslr_load(GR19C1,input_age_type = "BP")

# run EIV-CP model
set.seed(42)
GR19C1_EIVCP=reslr_mcmc(GR19C1_input,
           model_type = 'eiv_cp_t',
           n_cp=2)

# extract changepoints and slopes
cp = as.data.frame(GR19C1_EIVCP$noisy_model_run_output$BUGSoutput$sims.list$cp)
beta = as.data.frame(GR19C1_EIVCP$noisy_model_run_output$BUGSoutput$sims.list$beta)
save(cp,file='results/Belize/GR19C1_cp2_cp.Rdata')
save(beta,file='results/Belize/GR19C1_cp2_beta.Rdata')

# extract output RSL model
GR19C1_EIVCP_output = GR19C1_EIVCP$output_dataframes
write.csv(GR19C1_EIVCP_output,'results/Belize/GR19C1_EIVCP_cp2.csv')

# load output
GR19C1_EIVCP_output=read.csv('results/Belize/GR19C1_EIVCP_cp2.csv')
load('results/Belize/GR19C1_cp2_cp.Rdata')
load('results/Belize/GR19C1_cp2_beta.Rdata')

# summarise HDR for changepoints and slopes
calcHDR = function(cp,beta) {
  
  cp_hdr = data.frame()
  for (n in 1:ncol(cp)) {
    cp_lwr = 1950-as.numeric(hdrcde::hdr(x=cp[,n],prob=95)$hdr[,1])*1000
    cp_upr = 1950-as.numeric(hdrcde::hdr(x=cp[,n],prob=95)$hdr[,2])*1000
    
    cp_hdr_tobind = data.frame(lwr=cp_lwr,upr=cp_upr,cp=n)
    cp_hdr=bind_rows(cp_hdr,cp_hdr_tobind) 
  }
  
  beta_hdr = data.frame()
  for (n in 1:ncol(beta)) {
    
    beta_upr = as.numeric(hdrcde::hdr(x=beta[,n],prob=95)$hdr[,1])
    beta_lwr = as.numeric(hdrcde::hdr(x=beta[,n],prob=95)$hdr[,2])
    beta_mid = 0.5*(beta_upr+beta_lwr)
    beta_95err = 0.5*(beta_upr-beta_lwr)
    
    beta_hdr_tobind = data.frame(mid = beta_mid,err95 = beta_95err,beta=n)
    beta_hdr = bind_rows(beta_hdr,beta_hdr_tobind)
  }
  
  return(list(cp_hdr,beta_hdr))
}
GR19C1_EIVCP_HDR= calcHDR(cp,beta)

# plot
ggplot() +
  geom_rect(data=GR19C1,aes(xmin=Age-Age_up_er_2sd,xmax=Age+Age_up_er_2sd,
                            ymin=RSL-RSLer_up_2sd,ymax=RSL+RSLer_up_2sd),
            fill='transparent',color='lightskyblue',linewidth=0.1)+
  geom_path(data=GR19C1_EIVCP_output,aes(x=Age_BP,y=pred)) +
  geom_ribbon(data=GR19C1_EIVCP_output,aes(x=Age_BP,ymin=lwr,ymax=upr),alpha=0.3) +
  geom_density_ridges(data=cp,aes(x=1950-V1*1000,y=-13,scale=100),color=NA,alpha=0.6)+
  geom_density_ridges(data=cp,aes(x=1950-V2*1000,y=-13,scale=100),color=NA,alpha=0.6)+
  geom_errorbarh(data=GR19C1_EIVCP_HDR[[1]],
                aes(xmax=upr,xmin=lwr,y=-13.2,height=0.3)) +
  theme_classic()+
  scale_x_reverse() +
  labs(x='Age (yrs BP',y='RSL (m)')
  

```
# Spatio-temporal NI-GAM model

```{r run NIGAM model for Belize database}

# load Belize database
BelizeDatabase = read.csv('data/Belize Database 6Aug2025.csv') # errors in input file are 1-sigma

# collapse data to just one set of coordinates per region/ site.
BelizeDatabase = mutate(BelizeDatabase,coordinates = paste(Latitude,Longitude))
# For these regions, average mean location across all sites
toAvg = list('Region 1','Region 2','Region 3','Region 6','Region 7','Region 8')
AvgCoord = function(x) {
  subset=filter(BelizeDatabase,Site==x)
  subset = subset %>% mutate(Latitude=mean(Latitude),
                             Longitude=mean(Longitude)) %>% select(-coordinates)
  return(subset)
}
# For these locations, use coordinates of location with most data points
toPick = list('Region 4','Region 5')
ChooseCoord = function(x){
  subset=filter(BelizeDatabase,Site==x)
  subset = subset %>% group_by(coordinates) %>% mutate(site_count = n()) %>% ungroup()
  lat = unique(filter(subset,site_count==max(site_count))$Latitude)
  lon = unique(filter(subset,site_count==max(site_count))$Longitude)
  subset = subset %>% mutate(Latitude=lat,Longitude=lon) %>% select(-site_count,-coordinates)
  return(subset)
}
BelizeDatabaseGrouped = bind_rows(lapply(toAvg,AvgCoord) %>% rbindlist(),
                                  lapply(toPick,ChooseCoord) %>% rbindlist())
# export for Maeve 
write.csv(BelizeDatabaseGrouped,'data/Belize Database 6Aug2025 collapsed.csv')

BelizeDatabase_input=reslr_load(BelizeDatabaseGrouped,
                                input_age_type = "BP",
                                include_tide_gauge = FALSE,
                                include_linear_rate=TRUE, # Set this to TRUE for GIA (linear rate + linear rate err columns)
                                TG_minimum_dist_proxy = FALSE,
                                all_TG_1deg = FALSE)
plot(x = BelizeDatabase_input)


# # run decomposition
# Belize_nigam_decomp = reslr_mcmc(
# input_data = BelizeDatabase_input,
# model_type = "ni_gam_decomp",
# n_iterations = 2000
# )
# 
# # export output
# Belize_nigam_decomp_output = Belize_nigam_decomp$output_dataframes
# save(file='results/Belize_nigam_decomp_output.Rdata',Belize_nigam_decomp_output)

# load output
load('results/Belize_nigam_decomp_output.Rdata')

p_modelfit = plot(Belize_nigam_decomp,
     plot_type = "model_fit_plot",
     plot_caption = TRUE)
p_modelfit

p_decomp = plot(Belize_nigam_decomp,
     plot_type = "nigam_component_plot",
     plot_caption = TRUE)
p_decomp

plot(Belize_nigam_decomp,
     plot_type = "regional_plot",
     plot_caption = TRUE)

plot(Belize_nigam_decomp,
     plot_type = "regional_rate_plot",
     plot_caption = TRUE)


ggsave('figures/Belize/Belize_modelfit_6Aug2025.pdf',p_modelfit)
ggsave('figures/Belize/Belize_decomp_6Aug2025.pdf',p_decomp)

```


